[package]
name = "tcpip38"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
clap = "3.0.1"
pnet = "0.28.0"
rand = "0.8.4"
url = "2.2.2"
